### ISSUE TITLE
Error with null values

### ISSUE THREAD

**Issue by vinks** [FoundationMedicineInc/oracle-sage#20]
There is error in util.resultToJSON method, when value is NULL,

> Cannot read property 'constructor' of null

You need check value before call value.constructor.name

**Comment by mrchess** [comment]
Thanks. regression introduced in 0.3.0. Will fix it soon. If it's blocking you, downgrade to 0.2.x ... you just lose BLOB and RAW column type support.

**Comment by mrchess** [comment]
Fixed in 0.3.3.

**Comment by vinks** [comment]
Your fix now doesnt return any value to object, so it breaks consistency.
Normal object with values will be { foo: 'var' } all ok, if value of foo is NULL or 0, then you return empty object {} insted { foo: 0 } or { foo: null }
