### ISSUE TITLE
Null value removes attribute from returned object

### ISSUE THREAD

**Issue by vinks** [FoundationMedicineInc/oracle-sage#25]
Fix with null now doesnt return any value to object, so it breaks consistency.
Normal object with values will be { foo: 'var' } all ok, but if value of foo is NULL or 0, then you return empty object {} insted { foo: 0 } or { foo: null }

**Comment by mrchess** [comment]
Nice catch. Surprised we didn't run into this on our servers. Thanks for this one. Fix incoming.
