### ISSUE TITLE
upgrade oracledb and simple-oracledb dependencies.

### ISSUE THREAD

**Issue by sagiegurari** [FoundationMedicineInc/oracle-sage#3]
if you upgrade your oracledb version you will get promise support directly and you won't need to wrap it.
it also contains important fixes such as crash and memory leaks.

upgrading simple-oracledb is also important, there are also leak fix but you will also get few things that you implemented such as transactions, insert/update, batch and so on...
those capabilities are production proven and well tested.

so I recommend upgrading to latest release for both libraries and remove unneeded code to make your library simpler to maintain and remove unneeded dependencies such as bluebird to make your library lighter to install.

**Comment by mrchess** [comment]
These are a great round of suggestions. I will break these up into issues and address each of them!

**Comment by mrchess** [comment]
Upgraded. Will remove promises and stuff in a later update. Thanks!
