### ISSUE TITLE
Is this library maintened?

### ISSUE THREAD

**Issue by marcelotmagalhaes** [FoundationMedicineInc/oracle-sage#32]
Hello, I've just found this library and want to implement on a test project. Is this library still maintened? Also, is there any tutorial on how to connect and execute a simple query after it (I'm a little new to node and oracle)?

**Comment by marcelotmagalhaes** [comment]
Hi, I managed to connect and make a basic query. It is really more simple than appears.
But my doubt about if this library is still maintened persists, cause I liked it a lot and want to start working with sage.

**Comment by mrchess** [comment]
Were you about to resolve your #33 ?
Sorry, I've been in the dark. This library is indeed still maintained!
