### ISSUE TITLE
User class require problem

### ISSUE THREAD

**Issue by marcelotmagalhaes** [FoundationMedicineInc/oracle-sage#33]
Hello, I've created an User schema and tried to require inside the index, as the following:

User.js
```javascript
const sage = require('oracle-sage');


const userSchema = sage.Schema(
	{
		ID: 'number',
		CREATED_AT: {
			type: 'date',
			format: 'DD/MM/YYYY'
		},
		USERNAME: {
			type: 'varchar'
		},
		GENDER: {
			type: 'char',
			enum: {
				values: ['M', 'F']
			}
		},
		BIO: 'clob'
	},
	{
		primaryKey: 'ID'
	}
);

const userTable = 'users';
const User = sage.model(userTable, userSchema);

module.exports = User;
```

index.js
`const User = require('./models/User');`

Once I start the server, the following error appears:
`TypeError: Cannot call a class as a function`

Can anyone help me?

**Comment by mrchess** [comment]
Better late than never, I hope!
Were you able to figure this out?

It looks like you are forgetting to `new` up. It should be

`new sage.Schema` not `sage.Schema`
